version: '3.8'

volumes:
  mongo_vol:

networks:
  rotten_network:
    driver: bridge

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - rotten_network
    volumes:
      - mongo_vol:/data/db
      #- ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: admin_pwd
      #MONGO_INITDB_DATABASE: rotten_db
      #MONGO_INIT_DB_USERNAME: rotten_user
      #MONGO_INIT_DB_PASSWORD: rotten_pwd
      
  rotten-potatoes:
    container_name: rotten_potatoes
    image: luizmeier/rotten-potatoes:v1
    build:
      dockerfile: ./Dockerfile
      context: ./
    depends_on:
      - mongo
    ports:
      - 5000:5000
    networks:
      - rotten_network
    environment:
      MONGODB_USERNAME: admin_user
      MONGODB_PASSWORD: admin_pwd
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo
      MONGODB_DB: admin