apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-state
spec:
  serviceName: nginx-state
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: volume-page
          image: busybox
          #command: ['sh', '-c', 'echo $(hostname) > /usr/share/nginx/html/index.html']
          volumeMounts:
            - mountPath: /usr/share/nginx/html/index.html
              name: www2
      containers:
      - name: nginx-1
        image: nginx
        ports:
          - containerPort: 80
            name: web
        #volumeMounts:
        #- name: www2
        #  mountPath: /usr/share/nginx/html/index.html
  volumeClaimTemplates:
    - metadata:
        name: www2
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: default
        resources:
          requests:
            storage: "1Gi"