apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-juquinha-net-cert
spec:
  secretName: juquinha-net-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - "veronez.net"