version: '3.8'

volumes:
  mongo_vol:

networks:
  mongo_network:
    driver: bridge

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - mongo_network
    volumes:
      - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports: 
      - 8081:8081
    networks:
      - mongo_network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo