# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main
  
resources:
  - repo: self
  
variables:
  tag: $(Build.BuildId)
  imageName: 'pedelogo-catalogo'
  vmImageName: vm-jenkins
  
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
      vmImage: $(vmImageName)
    steps:
      
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: DockerHub

    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: lfmmeier/pedelogo-catalogo
        containerRegistry: DockerHub
        Dockerfile: $(Build.SourcesDirectory)/Dockerfile
        tags: |-
          $(tag)
          latest

    - task: Docker@2
      displayName: Logout of Docker Hub
      inputs:
        command: logout
        containerRegistry: DockerHub

    - task: PublishPipelineArtifact@1
      displayName: Publish Pipeline Artifact
      inputs:
        artifactName: api
        path: $(Build.SourcesDirectory)/k8s/api
