version: '3.8'
services:
  api:
    image: kubedevio/pedelogo-catalogo:v1.0.0
    ports:
      - "8080:80"
    networks:
      - pedelogo
    depends_on:
      - pedelogo-mongodb
    environment:
      Mongo__Host: "pedelogo-mongodb"
      Mongo__User: "mongouser"
      Mongo__Password: "mongopwd"
      Mongo__Port: "27017"
      Mongo__Database: "admin"
    volumes:
      - "./logs/api:/log"

  pedelogo-mongodb:
    image: mongo:4.1
    networks:
      - pedelogo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongouser"
      MONGO_INITDB_ROOT_PASSWORD: "mongopwd"

  loki:
    image: grafana/loki:2.0.0
    ports:
      - "3100:3100"
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true
    networks:
      - pedelogo

  promtail:
    image: grafana/promtail:2.0.0
    command: -config.file=/etc/prmtail/config.yml
    volumes:
      - "./promtail/config.yaml:/etc/prmtail/config.yml"
      - "./logs/api:/logs/api"
      - "./tmp:/tmp"
    networks:
      - pedelogo
    ports:
      - 9080:9080

#  mongoexporter:
#    image: fabricioveronez/mongo_exporter
#    ports:
#      - "9216:9216"
#    networks: 
#      - pedelogo
#    depends_on:
#      - pedelogo-mongodb
#    environment:
#      MONGODB_URI: "mongodb://mongouser:mongopwd@pedelogo-mongodb:27017"
#
#  prometheus:
#    image: prom/prometheus:v2.24.1
#    volumes:
#      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
#      - ./alert.rules.yaml:/etc/prometheus/alert.rules
#    ports:
#      - "9090:9090"
#    depends_on:
#      - api
#    networks:
#      - pedelogo
#
#  alertmanager:
#    image: prom/alertmanager:v0.21.0
#    ports:
#      - 9093:9093
#    volumes:
#      - ./alertmanager.yaml:/prometheus/alertmanager.yml
#    command:
#    - '--config.file=/prometheus/alertmanager.yml'
#    networks:
#      - pedelogo

networks:
  pedelogo:
    driver: bridge